services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - "./mongodb:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "27080:8081"
    links:
      - "mongodb"
    depends_on:
      - "mongodb"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
